variables:
  GIT_SUBMODULE_STRATEGY: "recursive"
  CMAKE_BUILD_TYPE: "Debug"
  CC: "/usr/bin/gcc-9"
  CXX: "/usr/bin/g++-9"
  GCOV: "/usr/bin/gcov-9"

image: gitlab.cachegrand.dev:5050/cachegrand/cachegrand-server/ubuntu-2004-x64-gcc:latest

stages:
  - build
  - test
  - codecoverage
  - deploy

build_ubuntu2004_x64_gcc9_debug:
  stage: build
  script:
    - cmake -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DUSE_HASHTABLE_HASH_ALGORITHM_T1HA2=1 -DBUILD_TESTS=1 -DBUILD_INTERNAL_BENCHES=1
    - cmake --build build -- -j $(nproc)
  artifacts:
    paths:
      - build
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - build/
    untracked: true
  tags:
    - ubuntu-2004
    - x64

test_ubuntu2004_x64_gcc9_debug:
  stage: test
  needs: [build_ubuntu2004_x64_gcc9_debug]
  script:
    - build/tests/cachegrand-tests
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - build/
    untracked: true
  tags:
    - ubuntu-2004
    - x64

codecoverage_ubuntu2004_x64_gcc9_debug:
  stage: codecoverage
  needs: [test_ubuntu2004_x64_gcc9_debug]
  variables:
    INPUT_REMOVE_PATTERNS: "3rdparty,tests,build/_deps"
    INPUT_OUTPUT_LCOV_INFO: "build/coverage.info"
  script:
    - chmod +x tools/docker/build/code-coverage.sh
    - INPUT_GCOV_PATH="${GCOV}" tools/docker/build/code-coverage.sh
    - genhtml -o build/coverage-html -p $(pwd) -s --legend build/coverage.info
  artifacts:
    paths:
      - build/coverage.info
      - build/coverage-html
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - build/
    untracked: true
  tags:
    - ubuntu-2004
    - x64

pages:
  stage: deploy
  dependencies:
    - codecoverage_ubuntu2004_x64_gcc9_debug
  script:
    - mv build/coverage-html public
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - build/
    untracked: true
  artifacts:
    paths:
      - public
    expire_in: 30 days
  tags:
    - x64
